### ISSUE TITLE
irrKlang 32-bit

### ISSUE THREAD

**Issue by gzito** [Shot511/GameBreakout#1]
The provided precompiled libs for irrKlang are for 32-bit version.
I'm building with CMake for VS 2019 and only 64-bit project was generated.
So the linker failed with the following message;

1>   Creating library C:/Users/g.zito/Documents/GitHub/GameBreakout/build/src/Debug/Breakout.lib and object C:/Users/g.zito/Documents/GitHub/GameBreakout/build/src/Debug/Breakout.exp
1>game.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class irrklang::ISoundEngine * __cdecl irrklang::createIrrKlangDevice(enum irrklang::E_SOUND_OUTPUT_DRIVER,int,char const *,char const *)" (__imp_?createIrrKlangDevice@irrklang@@YAPEAVISoundEngine@1@W4E_SOUND_OUTPUT_DRIVER@1@HPEBD1@Z) referenced in function "void __cdecl `dynamic initializer for 'SoundEngine''(void)" (??__ESoundEngine@@YAXXZ)
1>..\..\thirdparty\irrKlang-1.6.0\lib\Win32-visualStudio\irrKlang.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
1>C:\Users\g.zito\Documents\GitHub\GameBreakout\build\src\Debug\Breakout.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "Breakout.vcxproj" -- FAILED.

Any suggestions?

**Comment by gzito** [comment]
I manually added irrKLang 64-bit *.lib and it worked.
I had to update linked ibraries for vs project (the path change for 64-bit).
Unfortunately I don't know how to update CMakefile to support both 32 and 64 bit versions.

**Comment by tgalaj** [comment]
Hey,

Thank you for raising this issue. I've modified the CMake files so 64 bit version of this application should build fine. Pull the newest version from this repo and let me know if this solved the issue.

**Comment by gzito** [comment]
Hey,

it now works perfectly. Thank you very much!
