### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by lijun190422** [Shot511/GameBreakout#2]
The C compiler identification is MSVC 19.20.27508.1
The CXX compiler identification is MSVC 19.20.27508.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Found OpenGL: opengl32   
Using MSVC!
IrrKlang Found!
IRRKLANG_LIBRARY = C:/svn/GameBreakout-master/thirdparty/irrKlang-64bit-1.6.0/lib/Winx64-visualStudio/irrKlang.lib
IRRKLANG_INCLUDE_DIR = C:/svn/GameBreakout-master/thirdparty/irrKlang-64bit-1.6.0/include
**CMake Error at thirdparty/thirdparty.cmake:11 (add_subdirectory):
  The source directory

    C:/svn/GameBreakout-master/thirdparty/freetype2

  does not contain a CMakeLists.txt file.**
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)

FREETYPE_LIBRARY = freetype
FREETYPE_INCLUDE_DIR = C:/svn/GameBreakout-master/thirdparty/freetype2/include
Unable to find glfw, cloning...
fatal: not a git repository (or any of the parent directories): .git

CMake Error at thirdparty/thirdparty.cmake:35 (add_subdirectory):
  The source directory

    C:/svn/GameBreakout-master/thirdparty/glfw

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)

fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

Configuring incomplete, errors occurred!
See also "C:/svn/GameBreakout-master/build/CMakeFiles/CMakeOutput.log".

**Comment by tgalaj** [comment]
Have you cloned the repo with `--recursive` flag? If not then try calling the following commands in command line:

`git clone --recursive https://github.com/Shot511/GameBreakout.git`

or (for SSH)

`git clone --recursive git@github.com:Shot511/GameBreakout.git`

Moreover, I have updated the cmake files, so that they now automatically pull all the required submodules.

**Comment by lijun190422** [comment]
It is ok  with --recursive flag. Thanks!
